version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - '3000'
    command: npm run dev
    networks:
      - dev-network

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx
    ports:
      - 80:80
      
    tty: true
    restart: "on-failure"
    depends_on:
      - frontend

    networks:
      - dev-network

 
networks:
  dev-network:
      driver: bridge