# docker-compose.yml
version: '3'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev-network
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    tty: true
    restart: "on-failure"
    depends_on:
      - vue-app
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
